name: Dower Tefence
main: com.github.lmiljak.dowertefence.DowerTefence
version: 0.0.1-SNAPSHOT
commands:
  dt:
    description: |
      dt start - Starts a new game of Dower Tefence.
      dt accept - Accepts an invite from another player.
    usage: |
      /dt start [players]
      /dt accept <player>
    permission: DowerTefence.basic
    permission-message: You don't have permission to execute this command.
